# Generated by Django 6.0.3 on 2026-07-30 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('one_to_one', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LuggageBag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField(default=35)),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='luggage_bags', to='one_to_one.passenger')),
            ],
        ),
    ]
