# Generated by Django 6.0.7 on 2026-08-04 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainer_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='trainer',
            managers=[
            ],
        ),
    ]
