# Generated by Django 6.0.7 on 2026-07-30 16:30

import django.core.validators
import pokemon_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_app', '0003_remove_pokemon_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='description',
            field=models.TextField(default='Story unknown', validators=[django.core.validators.MinLengthValidator(5), django.core.validators.MaxLengthValidator(500)]),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='level',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1, 'YOU FOOL NO LOWER NUMBER!'), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='name',
            field=models.CharField(max_length=30, validators=[pokemon_app.validators.title_format_validate]),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='pokemon_type',
            field=models.CharField(default='Normal', max_length=20, validators=[pokemon_app.validators.title_format_validate]),
        ),
    ]
