# Generated by Django 6.0.7 on 2026-07-28 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokemon_type', models.CharField(default='Normal', max_length=20)),
                ('name', models.CharField(max_length=30)),
                ('level', models.IntegerField(default=5)),
                ('description', models.TextField(default='Story unknown')),
                ('is_caught', models.BooleanField(default=False)),
            ],
        ),
    ]
