# Generated by Django 6.0.7 on 2026-07-29 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_app', '0002_pokemon_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='test',
        ),
    ]
