# Generated by Django 6.0.3 on 2026-07-30 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('one_to_one', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_num', models.CharField(default='123HTC')),
                ('passengers', models.ManyToManyField(related_name='flights', to='one_to_one.passenger')),
            ],
        ),
    ]
