# Generated by Django 6.0.7 on 2026-08-04 14:47

import django.core.validators
import pokemon_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('move_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokemon_type', models.CharField(default='Normal', max_length=20, validators=[pokemon_app.validators.title_format_validate])),
                ('name', models.CharField(max_length=30, validators=[pokemon_app.validators.title_format_validate])),
                ('level', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1, 'YOU FOOL NO LOWER NUMBER!'), django.core.validators.MaxValueValidator(100)])),
                ('description', models.TextField(default='Story unknown', validators=[django.core.validators.MinLengthValidator(5), django.core.validators.MaxLengthValidator(500)])),
                ('is_caught', models.BooleanField(default=False)),
                ('moves', models.ManyToManyField(related_name='pokemon', to='move_app.move')),
            ],
        ),
    ]
