# Generated by Django 6.0.7 on 2026-08-05 16:21

import pokemon_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='pokemon_type',
            field=models.CharField(default='Normal', max_length=20, validators=[pokemon_app.validators.title_format_validate, pokemon_app.validators.validate_type]),
        ),
    ]
